image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restart Kurtosis Engine
    command: |
      kurtosis engine restart
      clear
  - name: Run Fake Package
    command: | 
      kurtosis run github.com/fake-package/fake-package-purely-for-analytics || kurtosis clean -a
      clear
  - name: Open Readme
    command: |
      code README.md
      clear
  - name: Source Autocomplete
    command: |
      source <(kurtosis completion bash)
      echo "source <(kurtosis completion bash)" >> ~/.bashrc
      clear  

ports:
  - name: Kurtosis Engine Grpc Listen
    port: 9710
    onOpen: ignore
  - name: Kurtosis Engine Grpc Proxy Listen
    port: 9710
    onOpen: ignore    